from marshmallow import Schema, fields

class IngredientsSchema(Schema):
    diet = fields.Str()
    ingredient = fields.Str()
    weight = fields.Decimal(2)
    cost = fields.Decimal(2)

class MovementsSchema(Schema):
    category = fields.Str()
    quantity = fields.Int()
    weight = fields.Decimal(2)
    cost = fields.Decimal(2)

class SalesSchema(Schema):
    group_num = fields.Str()
    quantity = fields.Int()
    avg_live_wt = fields.Decimal(2)
    avg_carcass_wt = fields.Decimal(2)
    avg_base_price_cwt = fields.Decimal(2)
    avg_vob_cwt = fields.Decimal(2)
    avg_value_cwt = fields.Decimal(2)
    avg_yield_per = fields.Decimal(2)
    avg_lean_per = fields.Decimal(2)

class GroupsSchema(Schema):
    group_num = fields.Str()
    group_type = fields.Str()
    status = fields.Str()
    producer = fields.Str()
    site = fields.Str()
    barn = fields.Str()
    open_date = fields.Date()
    close_date = fields.Date()
    ingredients = fields.Nested(IngredientsSchema)
    diets = fields.Nested(IngredientsSchema)
    movements = fields.Nested(MovementsSchema)
    sales = fields.Nested(SalesSchema)

class BudgetsSchema(Schema):
    budget_id = fields.Str()
    group_num = fields.Str()
    budget_type = fields.Str()
    group_type = fields.Str()
    producer = fields.Str()
    site = fields.Str()
    barn = fields.Str()
    start_date = fields.Date()
    close_date = fields.Date()
    wof_avg = fields.Decimal(1)
    wof_tot = fields.Decimal(1)
    start_num = fields.Int()
    start_avg_wt = fields.Decimal(1)
    market_num = fields.Int()
    gilt_num = fields.Int()
    discount_num = fields.Int()
    death_num = fields.Int()
    transport_death_num = fields.Int()
    transfer_num = fields.Int()
    market_avg_wt = fields.Decimal(1)
    gilt_avg_wt = fields.Decimal(1)
    discount_avg_wt = fields.Decimal(1)
    death_avg_wt = fields.Decimal(1)
    transport_death_avg_wt = fields.Decimal(1)
    transfer_avg_wt = fields.Decimal(1)
    market_avg_price_pig = fields.Decimal(2)
    gilt_avg_price_pig = fields.Decimal(2)
    discount_avg_price_pig = fields.Decimal(2)
    transfer_avg_price_pig = fields.Decimal(2)
    feed_conversion = fields.Decimal(4)
    yield_per = fields.Decimal(4)
    lean_per = fields.Decimal(4)
    market_std_dev_carcass_wt = fields.Decimal(4)
    load_avg_std_dev_carcass_wt = fields.Decimal(4)
    feed_grinding_rate = fields.Decimal(2)
    feed_delivery_rate = fields.Decimal(2)
    avg_feed_delivery_ton = fields.Decimal(1)
    trucking_market_rate = fields.Decimal(2)
    avg_trucking_market_pig = fields.Decimal(1)
    trucking_feeder_rate = fields.Decimal(2)
    avg_trucking_feeder_pig = fields.Decimal(1)
    rent_cost_week = fields.Decimal(2)
    pig_cost_pig = fields.Decimal(2)
    overhead_cost_pig = fields.Decimal(2)